# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client-without-internode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63lient-without-internode.proto\x12\x16\x63lientwithoutinternode\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb1\x01\n\x0fKeyValueService\x12N\n\x03Get\x12\".clientwithoutinternode.GetRequest\x1a#.clientwithoutinternode.GetResponse\x12N\n\x03Put\x12\".clientwithoutinternode.PutRequest\x1a#.clientwithoutinternode.PutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_without_internode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=58
  _globals['_GETREQUEST']._serialized_end=83
  _globals['_GETRESPONSE']._serialized_start=85
  _globals['_GETRESPONSE']._serialized_end=113
  _globals['_PUTREQUEST']._serialized_start=115
  _globals['_PUTREQUEST']._serialized_end=155
  _globals['_PUTRESPONSE']._serialized_start=157
  _globals['_PUTRESPONSE']._serialized_end=187
  _globals['_KEYVALUESERVICE']._serialized_start=190
  _globals['_KEYVALUESERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
